'use client';

import { useState } from 'react';
import { createClient } from '@/lib/supabase/client';

interface InvoiceMeta {
  va: string;
  business: string;
  period: string;
  hours: number;
  tasks: number;
  calls: number;
  efficiency: number;
  rate: number;
}

function buildInvoiceHTML(meta: InvoiceMeta): string {
  const total = (meta.hours * meta.rate).toFixed(2);
  const invoiceNo = `INV-${Date.now().toString(36).toUpperCase()}`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Invoice ${invoiceNo}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 13px; color: #1A1918; background: #fff; padding: 48px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; }
  .logo { font-size: 22px; font-weight: 700; color: #1B4332; letter-spacing: -0.5px; }
  .logo span { color: #40916C; }
  .meta { text-align: right; }
  .meta h1 { font-size: 18px; font-weight: 700; color: #1B4332; }
  .meta p { color: #6B6860; font-size: 12px; margin-top: 2px; }
  .parties { display: grid; grid-template-columns: 1fr 1fr; gap: 32px; margin-bottom: 36px; }
  .party h3 { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #A8A69E; margin-bottom: 6px; }
  .party p { font-size: 13px; color: #1A1918; line-height: 1.6; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
  th { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #A8A69E; padding: 0 0 8px; text-align: left; border-bottom: 1px solid #E8E6DF; }
  td { padding: 12px 0; border-bottom: 1px solid #E8E6DF; font-size: 13px; color: #1A1918; }
  td:last-child { text-align: right; font-weight: 600; }
  .total { display: flex; justify-content: flex-end; }
  .total-box { text-align: right; padding: 16px 0; min-width: 200px; }
  .total-box .label { font-size: 11px; color: #6B6860; margin-bottom: 4px; }
  .total-box .amount { font-size: 28px; font-weight: 700; color: #1B4332; letter-spacing: -0.5px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #E8E6DF; font-size: 11px; color: #A8A69E; }
  @media print {
    body { padding: 32px; }
    @page { margin: 0; }
  }
</style>
</head>
<body>
<div class="header">
  <div class="logo">Caldr<span>OS</span></div>
  <div class="meta">
    <h1>Invoice</h1>
    <p>${invoiceNo}</p>
    <p>${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
  </div>
</div>
<div class="parties">
  <div class="party">
    <h3>From</h3>
    <p>${meta.va}</p>
  </div>
  <div class="party">
    <h3>Bill to</h3>
    <p>${meta.business}</p>
  </div>
</div>
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Detail</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>VA Services — ${meta.period}</td>
      <td>${meta.hours}h @ £${meta.rate.toFixed(2)}/hr</td>
      <td>£${total}</td>
    </tr>
    <tr>
      <td>Tasks completed</td>
      <td>${meta.tasks} tasks · ${meta.efficiency}% efficiency</td>
      <td>—</td>
    </tr>
    <tr>
      <td>Calls logged</td>
      <td>${meta.calls} calls handled</td>
      <td>—</td>
    </tr>
  </tbody>
</table>
<div class="total">
  <div class="total-box">
    <div class="label">Total due</div>
    <div class="amount">£${total}</div>
  </div>
</div>
<div class="footer">
  <p>Payment terms: 30 days · Generated by Caldr OS · ${invoiceNo}</p>
</div>
</body>
</html>`;
}

export default function InvoiceGenerator() {
  const [rate, setRate] = useState('8.50');
  const [period, setPeriod] = useState('This week');
  const [printing, setPrinting] = useState(false);
  const [saved, setSaved] = useState(false);
  const supabase = createClient();

  const mock: InvoiceMeta = {
    va: 'Your Name', business: 'Business', period: '10–16 Apr 2026',
    hours: 32.5, tasks: 28, calls: 47, efficiency: 94, rate: parseFloat(rate) || 0,
  };
  const total = (mock.hours * mock.rate).toFixed(2);

  async function generatePDF() {
    if (printing) return;
    setPrinting(true);

    const html = buildInvoiceHTML(mock);

    // Open in a new window and trigger print-to-PDF
    const win = window.open('', '_blank', 'width=800,height=900');
    if (!win) { setPrinting(false); return; }

    win.document.write(html);
    win.document.close();

    win.onload = async () => {
      win.print();

      // Save record to invoices table
      try {
        const { data: { user } } = await supabase.auth.getUser();
        if (user) {
          const now = new Date();
          const weekAgo = new Date(now.getTime() - 7 * 86400000);
          await supabase.from('invoices').insert({
            user_id: user.id,
            business_id: 'demo-business-id',
            period_start: weekAgo.toISOString().split('T')[0],
            period_end:   now.toISOString().split('T')[0],
            hours_worked: mock.hours,
            hourly_rate:  mock.rate,
            tasks_count:  mock.tasks,
            calls_count:  mock.calls,
            efficiency_pct: mock.efficiency,
            status: 'draft',
          });
        }
      } catch {
        // Non-fatal
      }

      setSaved(true);
      setPrinting(false);
    };
  }

  return (
    <div style={{ padding: 16, background: 'var(--card)', borderRadius: 16, border: '1px solid var(--border)' }}>
      <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--ink)', marginBottom: 14 }}>Invoice Generator</div>

      <div style={{ display: 'flex', gap: 10, marginBottom: 14 }}>
        <div style={{ flex: 1 }}>
          <label style={{ fontSize: 11, fontWeight: 600, color: 'var(--ink-2)', display: 'block', marginBottom: 5 }}>Hourly rate (£)</label>
          <input
            value={rate}
            onChange={e => { setRate(e.target.value); setSaved(false); }}
            style={{ width: '100%', padding: '9px 12px', border: '1px solid var(--border)', borderRadius: 9, fontSize: 14, color: 'var(--ink)', background: 'var(--white)', outline: 'none', fontFamily: 'monospace', boxSizing: 'border-box' }}
          />
        </div>
        <div style={{ flex: 1 }}>
          <label style={{ fontSize: 11, fontWeight: 600, color: 'var(--ink-2)', display: 'block', marginBottom: 5 }}>Period</label>
          <select
            value={period}
            onChange={e => { setPeriod(e.target.value); setSaved(false); }}
            style={{ width: '100%', padding: '9px 12px', border: '1px solid var(--border)', borderRadius: 9, fontSize: 13, color: 'var(--ink)', background: 'var(--white)', outline: 'none' }}
          >
            {['This week', 'Last week', 'This month', 'Custom'].map(p => <option key={p}>{p}</option>)}
          </select>
        </div>
      </div>

      {/* Preview */}
      <div style={{ padding: 14, background: 'var(--white)', borderRadius: 12, border: '1px solid var(--border)', marginBottom: 14 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 10 }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--ink)' }}>{mock.va}</div>
          <div style={{ fontSize: 11, color: 'var(--ink-3)' }}>{mock.period}</div>
        </div>
        {[
          [`${mock.hours}h worked`, `£${total}`],
          [`${mock.tasks} tasks completed`, `${mock.efficiency}% efficient`],
          [`${mock.calls} calls logged`, ''],
        ].map(([l, r]) => (
          <div key={l} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', borderBottom: '1px solid var(--border)', fontSize: 12, color: 'var(--ink-2)' }}>
            <span>{l}</span>
            <span style={{ fontWeight: 600, color: 'var(--ink)' }}>{r}</span>
          </div>
        ))}
        <div style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 0 0', fontSize: 15, fontWeight: 700, color: 'var(--accent)' }}>
          <span>Total</span><span>£{total}</span>
        </div>
      </div>

      <button
        onClick={generatePDF}
        disabled={printing}
        style={{ width: '100%', padding: 12, background: printing ? 'var(--accent-light)' : 'var(--accent)', color: printing ? 'var(--accent)' : 'white', border: 'none', borderRadius: 11, fontSize: 13, fontWeight: 700, cursor: printing ? 'wait' : 'pointer', transition: 'all 0.2s' }}
      >
        {printing ? 'Opening PDF…' : saved ? '✓ Print / Save as PDF' : 'Generate Invoice PDF'}
      </button>
      {saved && <div style={{ fontSize: 11, color: 'var(--accent-mid)', textAlign: 'center', marginTop: 6 }}>Invoice record saved · Print dialog opened</div>}
    </div>
  );
}
